Build a regression model.

In [16]:
import pandas as pd
import statsmodels.api as sm

In [6]:
pd.set_option('display.max_rows', None)

In [10]:
# Reset display options to default values
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [11]:
df_chosen_var = pd.read_csv('../data/df_chosen_var.csv')
df_chosen_var

,number_of_bikes_avail,average_distance_fs,average_price_fs,average_popularity_fs,average_rating_fs,average_distance_yelp,average_price_yelp,average_popularity_yelp,average_rating_yelp
0,10,490.3,1.888889,0.970151,8.710000,540.318381,2.450000,388.95,4.125
1,5,390.6,2.000000,0.943919,8.310000,465.190825,1.937500,37.00,4.075
2,20,454.5,1.600000,0.964516,8.750000,726.882872,2.277778,461.15,4.275
3,4,655.9,2.111111,0.943036,7.400000,681.071769,2.181818,7.90,3.775
4,21,753.3,1.250000,0.956463,6.888889,771.595287,1.384615,8.55,3.425
...,...,...,...,...,...,...,...,...,...
155,22,473.7,1.600000,0.984520,8.340000,766.588555,2.210526,281.45,4.225
156,6,294.2,1.666667,0.980067,8.810000,461.230112,2.411765,274.30,4.125
157,2,212.7,2.111111,0.980142,8.620000,270.852431,2.052632,271.45,4.100
158,3,286.6,1.500000,0.965444,8.590000,457.547915,2.166667,409.70,4.200
159,20,305.6,1.888889,0.985401,8.600000,347.833475,2.210526,269.45,4.050

In [12]:
# Removing 1 row with a NaN value 
df_chosen_var_cleaned = df_chosen_var.dropna()
df_chosen_var_cleaned

,number_of_bikes_avail,average_distance_fs,average_price_fs,average_popularity_fs,average_rating_fs,average_distance_yelp,average_price_yelp,average_popularity_yelp,average_rating_yelp
0,10,490.3,1.888889,0.970151,8.710000,540.318381,2.450000,388.95,4.125
1,5,390.6,2.000000,0.943919,8.310000,465.190825,1.937500,37.00,4.075
2,20,454.5,1.600000,0.964516,8.750000,726.882872,2.277778,461.15,4.275
3,4,655.9,2.111111,0.943036,7.400000,681.071769,2.181818,7.90,3.775
4,21,753.3,1.250000,0.956463,6.888889,771.595287,1.384615,8.55,3.425
...,...,...,...,...,...,...,...,...,...
155,22,473.7,1.600000,0.984520,8.340000,766.588555,2.210526,281.45,4.225
156,6,294.2,1.666667,0.980067,8.810000,461.230112,2.411765,274.30,4.125
157,2,212.7,2.111111,0.980142,8.620000,270.852431,2.052632,271.45,4.100
158,3,286.6,1.500000,0.965444,8.590000,457.547915,2.166667,409.70,4.200
159,20,305.6,1.888889,0.985401,8.600000,347.833475,2.210526,269.45,4.050

In [20]:
# Create a function that will run a regression model with the x variables as inputs
def regression_modeling(x_vars):
    X = df_chosen_var_cleaned[x_vars]
    y = df_chosen_var_cleaned['number_of_bikes_avail']

    # Add a constant to the model
    X = sm.add_constant(X)

    # Create the model
    model = sm.OLS(y, X)

    # Fit the model
    results = model.fit()

    return results.summary()

In [21]:
# First model with all the x variables from Foursquare dataset
x_variables = ['average_distance_fs', 'average_price_fs', 'average_popularity_fs', 'average_rating_fs']
print(regression_modeling(x_variables))

                              OLS Regression Results
=================================================================================
Dep. Variable:     number_of_bikes_avail   R-squared:                       0.008
Model:                               OLS   Adj. R-squared:                 -0.018
Method:                    Least Squares   F-statistic:                    0.3038
Date:                   Wed, 13 Dec 2023   Prob (F-statistic):              0.875
Time:                           20:16:02   Log-Likelihood:                -507.18
No. Observations:                    159   AIC:                             1024.
Df Residuals:                        154   BIC:                             1040.
Df Model:                              4
Covariance Type:               nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    10.1908     15.683      0.650      0.517     -20.791      41.173
average_distance_fs       0.0002      0.003      0.056      0.955      -0.006       0.007
average_price_fs         -1.0615      1.717     -0.618      0.537      -4.453       2.330
average_popularity_fs    -8.1055     20.979     -0.386      0.700     -49.549      33.338
average_rating_fs         1.2167      1.205      1.010      0.314      -1.163       3.597
==============================================================================
Omnibus:                        7.276   Durbin-Watson:                   2.115
Prob(Omnibus):                  0.026   Jarque-Bera (JB):                7.430
Skew:                           0.499   Prob(JB):                       0.0244
Kurtosis:                       2.647   Cond. No.                     2.78e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.78e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [22]:
# Second model with all the x variables from Yelp dataset
x_variables = ['average_distance_yelp', 'average_price_yelp', 'average_popularity_yelp', 'average_rating_yelp']
print(regression_modeling(x_variables))

                              OLS Regression Results
=================================================================================
Dep. Variable:     number_of_bikes_avail   R-squared:                       0.059
Model:                               OLS   Adj. R-squared:                  0.035
Method:                    Least Squares   F-statistic:                     2.430
Date:                   Wed, 13 Dec 2023   Prob (F-statistic):             0.0501
Time:                           20:17:13   Log-Likelihood:                -502.94
No. Observations:                    159   AIC:                             1016.
Df Residuals:                        154   BIC:                             1031.
Df Model:                              4
Covariance Type:               nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                      -6.4469     12.736     -0.506      0.613     -31.607      18.714
average_distance_yelp       0.0015      0.003      0.552      0.582      -0.004       0.007
average_price_yelp         -3.9887      1.867     -2.137      0.034      -7.676      -0.301
average_popularity_yelp     0.0097      0.004      2.166      0.032       0.001       0.018
average_rating_yelp         5.6083      3.150      1.780      0.077      -0.615      11.831
==============================================================================
Omnibus:                        8.036   Durbin-Watson:                   2.132
Prob(Omnibus):                  0.018   Jarque-Bera (JB):                8.476
Skew:                           0.555   Prob(JB):                       0.0144
Kurtosis:                       2.779   Cond. No.                     1.84e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.84e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

Provide model output and an interpretation of the results.

# Stretch

How can you turn the regression model into a classification model?